spring:
  application:
    name: ProjetoPDS

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ProjetoPDS
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true